### ISSUE TITLE
Site additions

### ISSUE THREAD

**Issue by imurreflection** [xbmc-adult/xbmc-adult#155]
Hey Mate, hope you are doing fine and thank you for only regularly updated add-on on Kodi. I have gone through all available sites and my observations are below

Many sites like indianpornvideos, jav789,javbuz,javhihi,letfap,pornooxo,spankwire,and tukif are down from a long time.

We have also agreed that all JAV sites cannot be fixed because their playback algorithm has been changed and is quite complex for catcher.

Now, may I suggest to remove these sites and add some extremely high quality sites like

1) daftsex
2) Porntrex
3) Hclips
4) Indianmasalasex.net ( in place of  Indianpornvideos).
5) spankbang.com
6) javwhores.com ( replacement for Jav sites).
7) hqporner.com

I m sure addition of these sites will make our already best add-on much better. Regards.

**Comment by imurreflection** [comment]
Hi, mrdougquaid and nabilbendafi, Thank you so much for adding Porntrex. This is highly appreciated. However, please note that there are no images/pictures anywhere on add-on and without it, it's pretty much useless. On PC or Mobile browsers, I can see all pictures. Kindly fix it.

**Comment by Gujal00** [comment]
Porntrex issues fixed in #169

**Comment by imurreflection** [comment]
Hey mate, good to hear from you. Thank you so much for fixing Porntrex images issue. Now kindly add javwhores.com as a replacement for 4 Jav sites and remove all these non working sites. Thanks again

**Comment by Gujal00** [comment]
JAVWhores added in #170

**Comment by imurreflection** [comment]
Mate, you are a star. I have no words for what you are doing for this add-on and you are indeed irreplaceable. Thank you again

**Comment by Gujal00** [comment]
pornoxo and spankwire fixed in #170

**Comment by Gujal00** [comment]
@imurreflection Indianmasalasex.net pagination is no good. It can be done a single list with pagination but with no categories or sorting. And search will work only one page. Find some other site.

**Comment by imurreflection** [comment]
Thank you mate. No worries.  However, since six sites will not be available in next release onwards, may I suggest to add Spankbang, Daftsex, Hclips and Hqporner please. They are the best sites and in origin for a long time.

**Comment by nabilbendafi** [comment]
@imurreflection I have a branch https://github.com/nabilbendafi/xbmc-adult/commit/8ddc39cd38dc2f8b0cf8825dfc221b19357f2322 for adding DaftSex, but I struggle to write the video catcher for it.

[savevk.com](savekv.com) Can be use as "iframe grabber" 
But then the lines to parse are tricky

ex. for https://daftsex.com/watch/-131053344_456257946 the lines to parse are
```js
 window.videoParams = {
  id: "-131053344_456257946",
  server: "1JnLkV3bsNWe6Fmcj5iMtQTM2NHc",
  title: "Jessa Rhodes [PornMir, \u041f\u041e\u0420\u041d\u041e \u0412\u041a, new Porn vk, HD 1080, POV, Hardcore, Blowjob, Handjob, Deep Throat, Titjob, Pornstar]",
  description: "",
  duration: 3630,
  files: {"mp4_240":"240.z7qxVTML4_75DQTwPIuMJQ","mp4_360":"360.rkMG-OeqejJ6XzolBM_9oQ","mp4_720":"720.-RQrK2tMDstBtZ6EjR_q1Q"},
  i_key: "db4651c9"
};
```

1. We need to take the `id` and replace `_` by `/`
2. Grab _file_ token for the wanted resolution (ex. _240.z7qxVTML4_75DQTwPIuMJQ_)
3. Swap the resolution and token. And add `.mp4?extra=` in between
3. Compose 1 and 3 in final _url_ beging with _https://psv14-2.crazycloud.ru/videos/_

The final video URL will be https://psv14-2.crazycloud.ru/videos/-131053344/456257946/240.mp4?extra=z7qxVTML4_75DQTwPIuMJQ

@Gujal00 Do you know if it feasible with current url, ext_target, ext_url ... combination and so ? Or should I give up ?
Because if we could use Named capture group in regex, it should be possible to do such (complex) combinaison.

**Comment by Gujal00** [comment]
@nabilbendafi it is in the too hard basket with Videodevil catcher, In catcher you cannot split and substitute and do such things unfortunately

**Comment by nabilbendafi** [comment]
Thx for answer. Unfortunately

**Comment by Gujal00** [comment]
Please close this issue as whatever sites that could be added are done.

Looks like people just pull the list from uwc and request to be implemented here. There is a reason why these sites are not here and in uwc instead due to the nature of the catcher. SO can't implement whatever is there in uwc into Videodevil

**Comment by imurreflection** [comment]
You are correct mate but why people are requesting these sites is because UWC has been abandoned.  Porntrex has been added which raises the hopes for other site additions as well. Please see if Spankbang, Hclips and Hqporner can be added. I am sure with your expertise, it is quite possible. If not, please reply and I will close the issue. Have a nice day mate !!!

**Comment by nabilbendafi** [comment]
[HQporner](https://hqporner.com) should be added very soon. I have few thing to fix.

**Comment by imurreflection** [comment]
Thank you so much nabilbendafi bro
