### ISSUE TITLE
Site issues- Bitporno, Javwhores and Porntrex

### ISSUE THREAD

**Issue by imurreflection** [xbmc-adult/xbmc-adult#186]
Bitporno.com - not working
Javwhores- No next page in search Porntrex- Not Working

**Comment by Gujal00** [comment]
1. Bitporno is working okay aside from some occasional site server issues (Error 500). May be your ISP is blocking.
2. Javwhores next page issue on search results can't be fixed in Videodevil, as the page can't be regexed, it is a ajax query that needs to be built and Videodevil can't do such advanced stuff.
3. Porntrex seems to be working after @mrdougquaid reverted the last change

**Comment by imurreflection** [comment]
Ah .it's an irony that old technology is not able to accommodate new changes.  Without Next page the site is pretty useless as we have to rely on only provided content.  May be it's time now to adopt new technology. I am sure you, mrdougquaid and Nebalbendafi can do something about it.

**Comment by Gujal00** [comment]
The search page contains 75 results. If you use a proper search term then it will be within the first 75 results, stop saying it is unusable, just because there is no pagination possible for search results
@mrdougquaid please close this issue

**Comment by imurreflection** [comment]
I have been reporting issues to ensure our add-on remains the best. Looks like, it doesn't go well with you.  Please be assured that I will never report any issues now. Have a nice day Mate.

**Comment by Gujal00** [comment]
It is not that reporting issues a problem. It is even after explaining that certain things are not possible in this addon, you keep insisting on stuff from other addons. Reporting issues is always welcome, and if solution is not possible, please accept it and close the issue
