### ISSUE TITLE
Ashemaletube problem and solution and other problems

### ISSUE THREAD

**Issue by pedrocosta1970** [xbmc-adult/xbmc-adult#218]
Ashemaletube blocks addon. 

**1º Problem and Solution:**
Here:
item_infos=class="thumb-item.+?img\s*src="([^"]+).+?"([^"]+)"\s*title="([^"]+).+?wrapper"[^\d]+([\d:]+).+?wrapper"[^<]+<**/**

Delete / at de end:
item_infos=class="thumb-item.+?img\s*src="([^"]+).+?"([^"]+)"\s*title="([^"]+).+?wrapper"[^\d]+([\d:]+).+?wrapper"[^<]+<
 
**2º Problem:**

Some videos give error because they need login. Is it possible to implement this option?

**3º Problem:**

When we do Next Page, or we go to the Categories Section the first 2 results are always the same ...

**4º Problem:**

Not a problem, but it is possible to order by default as on the site, rather than alphabetical order?

Thanks.

**Comment by Gujal00** [comment]
1. There are 36 videos plus another 30 mosty commented videos on each page, so you end up with 66 videos on the list with your proposed regex and every page will have the same 30 videos. I have uploaded a fix which uses the mobile site, so it is clean but each page has only 12 videos.

2. This cannot be handled in videodevil unfortunately

3. this problem is related to 1 and is not present when mobile site is used

4. Videodevil always sorts the videos in alphabetical order. This is a global behaviour, that cant be changed

**Comment by pedrocosta1970** [comment]
Ok. Thanks.
