### ISSUE TITLE
Yespornplease

### ISSUE THREAD

**Issue by mywayorhighway0** [xbmc-adult/xbmc-adult#222]
Hey Good day to you all. Can you add yespornplease.com. good site with full length HD content

**Comment by Gujal00** [comment]
Another site from uwc. Please don't request sites from UWC to be implemented in Videodevil, most sites from UWC are not possible to be done in Videodevil

**Comment by mywayorhighway0** [comment]
This site is not there in Ultimate Whitecream. Can you please add it. If even after trying, its not possible then please leave it. Warm regards

**Comment by Gujal00** [comment]
The site is in UWC 1.1.64 and is hosted by tva in their tva-adult-repo

**Comment by mywayorhighway0** [comment]
The new version 1.1.65 has all issues fixed and this site is not there anymore. Why would anyone goes back to not working version. Can you at least try to add this site rather than simply denying. This is frustrating having to plead to developers

**Comment by mywayorhighway0** [comment]
My friend, please please please add this site. I assure you I will never request any site to be added from UWC again.

**Comment by Gujal00** [comment]
As usual with sites in UWC, the final videourl needs complex python code to deobfuscate the link hosted in vshare.io. Videodevil can only handle simple regex and it is impossible to add this into Videodevil due to this. Sorry

@mrdougquaid please close this request, unless someone is willing to develop a dedicated addon just for yespornplease

**Comment by mrdougquaid** [comment]
We have sufficient sites in videodevil already

**Comment by mrdougquaid** [comment]
What I meant was we won't add a dedicated addon for this site
