### ISSUE TITLE
FlashTranny.com / ShemaleModelstube.com

### ISSUE THREAD

**Issue by pedrocosta1970** [xbmc-adult/xbmc-adult#231]
If possible:

https://www.flashtranny.com/
and
https://shemalemodelstube.com/

Thanks.

**Comment by Gujal00** [comment]
flashtranny is using infinite scroll instead of pagination, so unable to be done in Videodevil
shemalemodelstube image server is using a ssl cert from a provider not trusted by Kodi, so unable to display the thumbnail images.
So Unfortunately both sites cannot be done for the time being

**Comment by DragEleven** [comment]
So that's why I could not get it to work,with my poor knowledge...:-)

I try:

flastranny.com.cfg
```
########################################################
# flashtranny.com VideoPortal
########################################################
start=https://www.flashtranny.com
catcher=flashtranny.com
########################################################
# Videos
########################################################
#item_infos=item">.+?title="([^"]+).+?ref="([^"]+).+?src="([^"]+).+?i>([:\d]+)</span>
#item_infos=class="b-thumb-item">.+?href="([^"]+).+?src="([^"]+).+?alt="([^"]+).+?i>([\d:]+)</span>
#item_infos=item">.+?href="([^"]+).+?src="([^"]+).+?alt="([^"]+)
item_infos=href="([^"]+).+?src="([^"]+).+?alt="([^"]+)
item_order=url|icon|title|title.append
item_info_name=title
item_info_build= (%s)
item_info_name=type
item_info_build=video
item_url_build=https://www.flashtranny.com%s
########################################################
```

catcher.list
```
########################################################
title=flashtranny.com
target=source\s*src="([^"]+)
url=%s
extension=mp4
quality=standard
########################################################
```


I couldn't do regex with time "duration"...but without, i have thumbnails, 133 videos,  but catcher don´t work... 



shemalemodelstube.com.cfg 

```
########################################################
# shemalemodelstube.com VideoPortal
########################################################
start=https://shemalemodelstube.com
catcher=shemalemodelstube.com
########################################################
# Videos
########################################################
item_infos=content-video">.+?href="([^"]+).+?src="([^"]+).+?alt="([^"]+).+?date">([^<]+)
item_order=url|icon|title|title.append
item_info_name=title.append
item_info_build= (%s)
item_info_name=type
item_info_build=video
item_url_build=%s
########################################################

```
catcher.list
```
########################################################
title=shemalemodelstube.com
target=source\s*src="([^"]+)
url=%s
extension=mp4
quality=high
########################################################
```


No thumbnails and catcher dont work...

But I dont Know what i´m doing...:-)

P.S: shemalemodelstube.com work on Kodi 17.6 but not Kodi 18.0...

**Comment by Gujal00** [comment]
@DragEleven 
For shemalemodelstube the thumbnails and video come from the same server `https://media.shemalemodelstube.com/` which uses a ssl cert not trusted by Kodi18
Kodi 17.6 may play video and display thumbnails as the ssl trust setup is different.

It does work in Kodi 18 (both thumbnails and video playback) if you insert the 'Let’s Encrypt Authority' certificate into Kodi System cacert.pem

**Comment by DragEleven** [comment]
Ok. I understand.

And with flashtranny.com, why don't play? Is because of infinite scroll like you said?

The source-code looks similar to shemalemodelstube.com...

`<source src="https://vcdn01.flashtranny.com/video1/a/a8/5ea1f10ba9d51b4d947d62995e616ca8.mp4?validfrom=1549202870&amp;validto=1549247870&amp;rate=660k&amp;hash=FHKbPSyCyM13BVLixBFusBJj26Y%3D" type="video/mp4">`

`<source src="https://media.shemalemodelstube.com/videos/5/c/4/f/3/5c4f351cb6d5dPhatida-1.mp4" type='video/mp4'>`

is the catcher.list wrong?

And the refex is not perfect...

But even so...Show 133 videos...thumbnails...and kodi don't show error...only in log...but i don´t know what it means...:-) 

Thanks

**Comment by Gujal00** [comment]
you need to replace `&amp;` with `&` in that videolink for it to play. look for the `action=` keyword in catcher and try the ones available to see if it works, if not would need a new action to clean it up

**Comment by pedrocosta1970** [comment]
It seems I suggested 2 complicated websites. thanks for the effort.

**Comment by DragEleven** [comment]
@Gujal00 
It's very advanced for me. I don´t know how to replace "&amp" with &...in this regex of catcher.list:

`target=source\s*src="([^"]+)`

P.S: OK...OK...OK

action=decode   works...

**Comment by Gujal00** [comment]
@mrdougquaid 
1. Uses AJAX for pagination (infinite scrolling)
2. Uses a cert issued by a CA not trusted by kodi
I think this request can be closed as cannot be done in Videodevil
